package com.example.horoscopoapp.models

import androidx.annotation.Nullable
import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName="tsignozodiaco")
data class SignoZodiaco(
    //TODO: estudiar el autogenerated=false, va a ser más óptimo que el gestor de BD cree el id
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name="zod_id")
    val signoZodiacoId: Int = 0,
    @ColumnInfo(name="zod_nombre")
    @Nullable
    val nombre: String?
){
    constructor(nombre: String?): this(0, nombre)
}


